# Generated by Django 2.2.10 on 2020-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('combustible', models.CharField(choices=[('G', 'Gasolina'), ('D', 'Diesel'), ('H', 'Hibrido')], max_length=1)),
                ('motor', models.CharField(choices=[('B', 'Basic - 130CV'), ('N', 'Normal - 190CV'), ('A', 'AMG - 280CV')], max_length=1)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
