# Generated by Django 2.2.10 on 2020-05-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_auto_20200507_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasea',
            name='combustible',
            field=models.CharField(choices=[('Diesel', 'Diesel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clasea',
            name='motor',
            field=models.CharField(choices=[('Basic', 'Basic - 130CV'), ('Normal', 'Normal - 190CV'), ('AMG', 'AMG - 280CV')], max_length=1),
        ),
        migrations.AlterField(
            model_name='claseamg',
            name='combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina')], max_length=1),
        ),
        migrations.AlterField(
            model_name='claseamg',
            name='motor',
            field=models.CharField(choices=[('AMG', 'AMG - 620CV')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clasegle',
            name='combustible',
            field=models.CharField(choices=[('Hibrido', 'Hibrido')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clasegle',
            name='motor',
            field=models.CharField(choices=[('Normal', 'Normal - 260CV'), ('AMG', 'AMG - 400CV')], max_length=1),
        ),
    ]
