# Generated by Django 2.2.10 on 2020-05-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_auto_20200507_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('articulo', models.CharField(max_length=50)),
            ],
        ),
    ]
